Repository pysal/momepy, pull requests merged in 2022-09, with the labels that each got.

#371 ENH: geometry-based simplification of roundabouts
  docs/api.rst
  momepy/datasets/tests.gpkg
  momepy/preprocessing.py
  tests/test_preprocess.py
Labels: GSoC 2022

#389 handle scenarios leading to dimensions.StreetProfile() warnings
  momepy/dimension.py
Labels: rough edge

#395 handle `All NaN slice` warning
  ci/envs/38-minimal.yaml
  momepy/diversity.py
  momepy/utils.py
  tests/test_utils.py
Labels: rough edge

#398 Fix various warnings
  momepy/dimension.py
  momepy/diversity.py
  tests/test_elements.py
Labels: rough edge

#400 standardize pytest.approx() in testing files
  tests/test_dimension.py
  tests/test_diversity.py
  tests/test_intensity.py
  tests/test_shape.py
Labels: admin/maint, testing/CI, rough edge

#405 Run user guide tests with Python 3.10
  .coveragerc
  .github/workflows/tests.yaml
  .pre-commit-config.yaml
  ci/envs/310-dev.yaml
  ci/envs/310-latest.yaml
  ci/envs/38-minimal.yaml
  ci/envs/39-latest.yaml
  environment.yml
  requirements.txt
Labels: admin/maint, testing/CI

#403 remove pygeos duplicate
  asv.conf.json
Labels: documentation, rough edge

#404 bump copyright year
  docs/conf.py
Labels: documentation, admin/maint

#407 CI: test preprocessing part of user guide
  ci/envs/test_user_guide.sh
Labels: documentation, testing/CI

#410 minor spelling and punctuation update
  momepy/elements.py
Labels: documentation, rough edge

#413 add flake8 and isort to CI
  .pre-commit-config.yaml
  benchmarks/bench_dimension.py
  benchmarks/bench_distribution.py
  benchmarks/bench_diversity.py
  benchmarks/bench_elements.py
  benchmarks/bench_graph.py
  benchmarks/bench_intensity.py
  benchmarks/bench_shape.py
  benchmarks/bench_utils.py
  momepy/distribution.py
  momepy/diversity.py
  momepy/elements.py
  momepy/intensity.py
  momepy/preprocessing.py
  momepy/utils.py
  setup.cfg
  setup.py
  tests/test_elements.py
  tests/test_preprocess.py
  tests/test_utils.py
Labels: admin/maint, testing/CI

#418 GHA: update PyPI release action
  .github/workflows/release_to_pypi.yml
Labels: admin/maint

#416 Scour docs for consistency, grammar, etc.
  momepy/coins.py
  momepy/dimension.py
  momepy/distribution.py
  momepy/diversity.py
  momepy/elements.py
  momepy/graph.py
  momepy/intensity.py
  momepy/shape.py
  momepy/utils.py
  momepy/weights.py
Labels: documentation

#419 proof README.md
  README.md
Labels: documentation

#420 Add pyproject.toml file
  .github/workflows/release_to_pypi.yml
  pyproject.toml
  readthedocs.yml
  setup.cfg
  setup.py
Labels: admin/maint

#425 Make corrections in doc references
  docs/_static/references.bib
Labels: documentation

#427 resolves bug in Percentiles append.
  momepy/diversity.py
  tests/test_diversity.py
Labels: bug
