Repository pysal/momepy, pull requests merged in 2023-11, with the labels that each got.

#516 GHA: update actions
  .github/dependabot.yml
  .github/workflows/release_to_pypi.yml
  .github/workflows/tests.yaml
Labels: admin/maint

#517 MAINT: update required versions, adapt CI, lint for new target Python
  .github/workflows/tests.yaml
  ci/envs/310-latest.yaml
  ci/envs/310-oldest.yaml
  ci/envs/312-dev.yaml
  ci/envs/312-latest.yaml
  momepy/coins.py
  momepy/dimension.py
  momepy/distribution.py
  momepy/diversity.py
  momepy/elements.py
  momepy/preprocessing.py
  momepy/tests/test_elements.py
  momepy/tests/test_graph.py
  momepy/tests/test_intensity.py
  momepy/tests/test_preprocess.py
  momepy/tests/test_utils.py
  momepy/utils.py
  momepy/weights.py
  pyproject.toml
Labels: admin/maint, testing/CI

#518 RLS: add a changelog for 0.7.0
  CHANGELOG.md
Labels: release

#522 support strings in `elements.get_node_id()`
  momepy/elements.py
  momepy/tests/test_elements.py
Labels: bug
