Repository pysal/momepy, pull requests merged in 2024-04, with the labels that each got.

#566 ENH: street_alignment and get_nearest_street
  momepy/functional/_distribution.py
  momepy/functional/_elements.py
  momepy/functional/tests/test_distribution.py
  momepy/functional/tests/test_elements.py
Labels: enhancement

#567 TYP: consistency in typing
  momepy/functional/_distribution.py
  momepy/functional/_elements.py
Labels: admin/maint

#570 ENH: describe as a replacement of AverageCharacter
  momepy/__init__.py
  momepy/dimension.py
  momepy/diversity.py
  momepy/functional/_diversity.py
  momepy/functional/tests/conftest.py
  momepy/functional/tests/test_distribution.py
  momepy/functional/tests/test_diversity.py
  momepy/functional/tests/test_shape.py
  momepy/tests/test_utils.py
  momepy/utils.py
Labels: enhancement, refactor

#572 functional courtyards calculation
  momepy/__init__.py
  momepy/functional/_intensity.py
  momepy/functional/tests/test_intensity.py
Labels: refactor

#574 MAINT: compatibility, warning cleanup, test lint
  momepy/coins.py
  momepy/dimension.py
  momepy/elements.py
  momepy/functional/_elements.py
  momepy/functional/tests/test_elements.py
  momepy/intensity.py
  momepy/preprocessing.py
  momepy/tests/test_dimension.py
  momepy/tests/test_distribution.py
  momepy/tests/test_diversity.py
  momepy/tests/test_elements.py
  momepy/tests/test_graph.py
  momepy/tests/test_intensity.py
  momepy/tests/test_preprocess.py
  momepy/tests/test_shape.py
  momepy/tests/test_utils.py
  momepy/tests/test_weights.py
  momepy/utils.py
  momepy/weights.py
  pyproject.toml
Labels: admin/maint, testing/CI
