Repository pysal/momepy, pull requests merged in 2024-07, with the labels that each got.

#638 TST: update for changes in GEOS
  momepy/functional/_dimension.py
  momepy/functional/_distribution.py
  momepy/functional/_shape.py
  momepy/functional/tests/conftest.py
  momepy/functional/tests/test_distribution.py
  momepy/functional/tests/test_diversity.py
  momepy/functional/tests/test_shape.py
  momepy/tests/test_distribution.py
Labels: testing/CI

#644 ENH: add flow mode to COINS
  momepy/coins.py
  momepy/tests/test_coins.py
Labels: enhancement

#645 BUG: fix ordering of closed loops in remove_false_nodes
  momepy/preprocessing.py
  momepy/tests/test_preprocess.py
Labels: bug

#646 ENH: allow extraction of coins ends in COINS.stroke_attribute
  momepy/coins.py
  momepy/tests/test_coins.py
Labels: enhancement

#643 Approximate shared walls
  momepy/functional/_distribution.py
  momepy/functional/tests/test_distribution.py
Labels: enhancement

#647 BUG: check loops in remove_false_nodes against any node degree
  momepy/preprocessing.py
Labels: bug

#649 expose buffer variable
  momepy/functional/_dimension.py
  momepy/functional/_intensity.py
  momepy/functional/tests/test_dimension.py
  momepy/functional/tests/test_intensity.py
Labels: enhancement

#650 bump libpysal requirement to 4.12
  ci/envs/310-latest.yaml
  ci/envs/310-oldest.yaml
  ci/envs/311-latest.yaml
  ci/envs/312-latest.yaml
  ci/envs/312-min.yaml
  docs/environment.yml
  docs/install.rst
  environment.yml
  pyproject.toml
Labels: dependencies

#648 TST: Fix expected test values when using higher_order
  momepy/functional/tests/test_diversity.py
  momepy/weights.py
Labels: testing/CI

#651 DOC: reflect changes in RTD
  docs/conf.py
Labels: documentation
