Repository pysal/momepy, pull requests merged in 2024-01, with the labels that each got.

#533 CI/TST: fix test, rm log action, ruff-format
  .github/workflows/tests.yaml
  .pre-commit-config.yaml
  momepy/preprocessing.py
  momepy/shape.py
  momepy/tests/test_elements.py
  momepy/utils.py
  pyproject.toml
Labels: testing/CI

#532 ENH: first bits of refactored dimension
  ci/envs/310-latest.yaml
  ci/envs/310-oldest.yaml
  ci/envs/311-latest.yaml
  ci/envs/312-dev.yaml
  ci/envs/312-latest.yaml
  docs/install.rst
  environment.yml
  momepy/__init__.py
  momepy/functional/__init__.py
  momepy/functional/_dimension.py
  momepy/functional/tests/__init__.py
  momepy/functional/tests/test_dimension.py
  pyproject.toml
Labels: enhancement

#535 DOC: add links to discord
  README.md
  docs/index.rst
Labels: documentation

#377 ENH: improved node consolidation functions
  docs/api.rst
  docs/user_guide/preprocessing/consolidate_intersections.ipynb
  docs/user_guide/preprocessing/preprocessing.rst
  momepy/datasets/__init__.py
  momepy/datasets/nyc_graph.graphml
  momepy/preprocessing.py
  momepy/tests/test_preprocess.py
Labels: GSoC 2022

#542 CI: test on Apple Silicon
  .github/workflows/tests.yaml
Labels: testing/CI
