Repository pysal/momepy, pull requests merged in 2024-06, with the labels that each got.

#406 API: deprecation decorators for transition to functional API
  momepy/dimension.py
  momepy/tests/test_dimension.py
  momepy/utils.py
Labels: refactor

#580 Functional blocks
  momepy/functional/_elements.py
  momepy/functional/tests/test_elements.py
Labels: refactor

#589 Functional percentiles
  momepy/functional/_diversity.py
  momepy/functional/tests/conftest.py
  momepy/functional/tests/test_diversity.py
Labels: refactor

#594 DEP: bump libpysal minimum to 4.11
  ci/envs/310-latest.yaml
  ci/envs/310-oldest.yaml
  ci/envs/311-latest.yaml
  ci/envs/312-dev.yaml
  ci/envs/312-latest.yaml
  ci/envs/312-min.yaml
  docs/install.rst
  environment.yml
  pyproject.toml
Labels: dependencies

#586 Functional density
  momepy/functional/tests/test_diversity.py
  momepy/functional/tests/test_intensity.py
Labels: refactor

#588 Functional distribution
  momepy/functional/_distribution.py
  momepy/functional/tests/test_distribution.py
Labels: refactor

#587 Functional dimension
  momepy/functional/_dimension.py
  momepy/functional/tests/test_dimension.py
  momepy/functional/tests/test_diversity.py
Labels: refactor

#581 Functional diversity
  momepy/functional/_diversity.py
  momepy/functional/tests/test_diversity.py
Labels: refactor

#584 _describe API refactoring
  momepy/functional/_diversity.py
  momepy/functional/tests/test_diversity.py
  momepy/functional/tests/test_intensity.py
  momepy/intensity.py
  momepy/tests/test_intensity.py
Labels: refactor

#583 Functional arearatio
  momepy/functional/tests/test_intensity.py
Labels: refactor

#593 Street profile
  momepy/functional/_dimension.py
  momepy/functional/tests/test_dimension.py
Labels: refactor

#596 COMPAT: numpy 2.0 compatibility
  .github/workflows/tests.yaml
  ci/envs/312-dev.yaml
  momepy/functional/_dimension.py
  momepy/functional/_diversity.py
  momepy/functional/_shape.py
  momepy/functional/tests/test_distribution.py
  momepy/preprocessing.py
Labels: dependencies

#597 DOC: rework API docs around the new functional stuff
  .gitignore
  docs/_static/references.bib
  docs/api.rst
  docs/conf.py
  docs/legacy_api.rst
  docs/user_guide/getting_started.ipynb
  momepy/coins.py
  momepy/functional/_diversity.py
  momepy/functional/_elements.py
  momepy/preprocessing.py
Labels: documentation

#598 DOC: note on a precision issue in enclosed_tessellation
  momepy/functional/_elements.py
Labels: documentation

#604 gha for release notes - #543
  .github/release.yml
  .github/workflows/release_to_pypi.yml
  CHANGELOG.md
  docs/changelog.rst
  docs/index.rst
Labels: admin/maint, release

#607 Update `release.yml` - troubleshoot release action failure
  .github/release.yml
Labels: admin/maint

#608 BUG: fix describe_ function when count is not present
  momepy/functional/_diversity.py
  momepy/functional/tests/test_diversity.py
Labels: bug

#614 update precommit to ruff docs dir
  .pre-commit-config.yaml
Labels: admin/maint

#615 DOC: remaining examples in the new API
  momepy/functional/_dimension.py
  momepy/functional/_distribution.py
  momepy/functional/_elements.py
  momepy/functional/_shape.py
Labels: documentation

#616 DOC: expose get_nearest_node, fix fmt
  docs/api.rst
  docs/legacy_api.rst
  momepy/functional/_diversity.py
Labels: documentation

#617 API: allow silencing of FutureWarnings from legacy API
  docs/legacy_api.rst
  momepy/tests/test_utils.py
  momepy/utils.py
Labels: api

#618 minor type hinting fix
  momepy/functional/_diversity.py
Labels: admin/maint

#619 API: deprecate legacy API in favour of Graph-based functional implementation
  .github/workflows/tests.yaml
  momepy/dimension.py
  momepy/distribution.py
  momepy/diversity.py
  momepy/elements.py
  momepy/intensity.py
  momepy/shape.py
  momepy/tests/test_dimension.py
  momepy/tests/test_intensity.py
  momepy/tests/test_utils.py
  momepy/weights.py
Labels: deprecation

#620 ENH: add mean_deviation
  docs/api.rst
  momepy/distribution.py
  momepy/functional/_diversity.py
  momepy/functional/tests/test_diversity.py
Labels: enhancement

#623 TYP: add type hints to the graph module
  momepy/graph.py
Labels: admin/maint

#624 DOC: update docstrings to match numpy2 outputs
  momepy/functional/_dimension.py
  momepy/functional/_shape.py
Labels: documentation

#628 DOC: User guide fixes for elements examples
  docs/user_guide/elements/blocks.ipynb
  docs/user_guide/elements/enclosed.ipynb
  docs/user_guide/elements/links.ipynb
  docs/user_guide/elements/tessellation.ipynb
Labels: documentation

#634 CI: bump minimal requirements as per SPEC 0
  ci/envs/310-oldest.yaml
  environment.yml
  pyproject.toml
Labels: testing/CI, dependencies

#632 BUG: refactor computation of angles in COINS
  docs/user_guide/graph/coins.ipynb
  momepy/coins.py
  momepy/tests/test_coins.py
Labels: bug
